apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "copy-namespace-labels.jimmyray.io"
spec:
  namespaceSelector:
    matchExpressions:               
    - key: policy
      operator: In
      values: ["enabled"]
  type: Mutating
  operations: ["CREATE"]
  resources: ["pods"]
  javascript: |
    // this webhook will copy the namespace labels to pods
    const namespace = get("Namespace", "v1", request.namespace);
    const excludes = ['pod-security.kubernetes.io/audit','pod-security.kubernetes.io/enforce',
    'pod-security.kubernetes.io/warn','policy','kubernetes.io/metadata.name']

    // copy labels from namespace, remove excluded labels
    request.object.metadata.labels = namespace?.metadata?.labels;

    for (var key in request.object.metadata.labels) {
      if (excludes.includes(key)) {
        delete request.object.metadata.labels[key]
      }
    }

    // automatically calculate patch and exit
    mutate(request.object);

