.DEFAULT_GOAL := up

.PHONY:	up
up:
	./up.sh

.PHONY:	down
down:
	./down.sh

.PHONY:	test
test:
	tests/tests.sh

.PHONY:	wipe-k8s
wipe-k8s:
	./wipe-k8s.sh

.PHONY:	policies-up
policies-up:
	./policies-up.sh

.PHONY:	policies-down
policies-down:
	./policies-down.sh
