apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/component: AdmissionController
    app.kubernetes.io/instance: c7n-kates
    app.kubernetes.io/managed-by: c7n
    app.kubernetes.io/name: c7n-kates
    app.kubernetes.io/part-of: c7n_kube
    app.kubernetes.io/version: 0.2.27
  name: c7n-admission
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: <CA_BUNDLE>
    url: https://c7n-admission:8443/mutation
  failurePolicy: Fail
  name: admission.cloudcustodian.io
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None

