apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-cleanup-deploys
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno-cleanup-controller
rules:
  - verbs:
      # - get
      - list
      # - update
      # - watch
      - delete
    apiGroups:
      - "apps"
    resources:
      - deployments

