apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-deny-all-networkpolicy
spec:
  rules:
  - name: generate-deny-all-networkpolicy
    match:
      any:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kyverno
          - default
          - kube-public
    generate:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      name: deny-all
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress