apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: us-east-2
  version: "1.22"
  tags:
    owner: jimmyray
    env: dev
    billing: lob-cc

iam:
  withOIDC: true

secretsEncryption:
  keyARN: "arn:aws:kms:us-east-2:123456789012:key/9e23ba0e-f90a-46f7-889e-2ff55d53f2ef"